name: Aegis CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache Pip Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Lint with Ruff
        run: ruff check .

      - name: Run Unit Tests with Coverage
        # This now runs pytest and tells it to generate a coverage.xml report
        run: pytest --cov=aegis --cov-report=xml

      - name: Generate Test Data
        run: |
          export NUM_RECORDS=10000
          python scripts/generate_data.py

      - name: Run PySpark Pipeline (Integration Test)
        run: |
          python aegis/pipeline.py

      # --- NEW ARTIFACT UPLOAD STEP ---
      - name: Upload Run Artifacts
        # This action runs 'always()', so even if a previous step fails,
        # it will try to upload the reports for debugging.
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-artifacts
          path: |
            run_summary.json
            coverage.xml
