name: Aegis CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Run on a clean Linux machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Lint with Ruff
        run: |
          # The --select and --target-version are already in pyproject.toml,
          # but we can be explicit for critical checks. We will add the 'check'
          # subcommand and separate the --format argument.
          ruff check --select E9,F63,F7,F82 .
          # For the main check, we just run 'ruff check' and it will use
          # the settings from our pyproject.toml file.
          ruff check .

      - name: Generate Test Data
        run: |
          # We use an environment variable to override the default record count for a fast test
          export NUM_RECORDS=10000
          python scripts/generate_data.py

      - name: Run PySpark Pipeline
        run: |
          python aegis/pipeline.py
