name: Aegis CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Run on a clean Linux machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Lint with Ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff check --format=github --select=E9,F63,F7,F82 --target-version=py39 .
          # default ruff run with common checks
          ruff check --format=github --target-version=py39 .

      - name: Generate Test Data
        run: |
          # We use an environment variable to override the default record count for a fast test
          export NUM_RECORDS=10000
          python scripts/generate_data.py

      - name: Run PySpark Pipeline
        run: |
          python aegis/pipeline.py
